setup = { cmd = [
    { cmd = "git checkout main && git pull", working_dir = "crates/com-banan" },
    { cmd = "git checkout main && git pull", working_dir = "crates/com-banan-frontend" },
    { cmd = "git checkout main && git pull", working_dir = "crates/com-banan-tauri" }
] }
