name: "release"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install tauri cli
        run: cargo install tauri-cli
      - name: install app dependencies and build it
        run: cd crates/com-banan-frontend && yarn && cd ../..
      - name: build the app
        run: cd crates/com-banan-tauri && cargo tauri build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: matrix.platform == 'ubuntu-latest'
        with:
          files: |
            target/release/bundle/appimage/*.AppImage
            target/release/bundle/deb/*.deb
            LICENSE
